apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      environment: dev
    includeSelectors: false

patches:
  - target:
      version: v1
      kind: Namespace
      name: backend
    path: psa-backend.yaml
  - target:
      version: v1
      kind: Namespace
      name: database
    path: psa-database.yaml
  - target:
      version: v1
      kind: Namespace
      name: frontend
    path: psa-frontend.yaml
  - target:
      version: v1
      kind: Namespace
      name: vault
    path: psa-vault.yaml
