resourcePolicy:
  enabled: false
  keep:
    resourceQuota: true
    limitRange: true
    networkPolicy: true

resourceQuota:
  enabled: true
  hard:
    requests.cpu: "1"
    requests.memory: "2Gi"
    limits.cpu: "2"
    limits.memory: "4Gi"
    pods: "10"
    services: "4"
    configmaps: "3"
    secrets: "2"
    persistentvolumeclaims: "2"

limitRange:
  enabled: true
  limits:
    - type: Container
      defaultRequest:
        cpu: "100m"
        memory: "256Mi"
      default:
        cpu: "250m"
        memory: "512Mi"
      min:
        cpu: "50m"
        memory: "128Mi"
      max:
        cpu: "1"
        memory: "2Gi"

networkPolicy:
  defaultDeny:
    enabled: true
    policyTypes:
      - Ingress
      - Egress
    annotations: {}
  allowDNS:
    enabled: true
    annotations: {}