apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-vault-agent-config
  namespace: backend
data:
  config.hcl: |
    exit_after_auth = false
    pid_file = "/home/vault/.pid"

    vault {
      address        = "https://vault.vault.svc:8200"
      ca_cert        = "/vault/ca/vault.ca"
      tls_server_name = "vault-0.vault-internal"
    }
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role       = "backend"
          token_path = "/var/run/secrets/tokens/vault-token"
        }
      }

      sink "file" {
        config = {
          path = "/home/vault/.vault-token"
        }
      }
    }

    template {
      source      = "/etc/vault/database-creds.tpl"
      destination = "/vault/secrets/database-creds.txt"
    }

    template_config {
      exit_on_retry_failure = true
    }

  database-creds.tpl: |
    {{- with secret "database/creds/backend-role" -}}
    SPRING_DATASOURCE_USERNAME={{ .Data.username }}
    SPRING_DATASOURCE_PASSWORD={{ .Data.password }}
    {{- end }}
