apiVersion: v1
kind: ResourceQuota
metadata:
  name: backend-quota
  namespace: backend
spec:
  hard:
    requests.cpu: "3"
    requests.memory: "5Gi"
    limits.cpu: "6"
    limits.memory: "8Gi"
    pods: "12"
    services: "4"
    configmaps: "3"
    secrets: "4"
    persistentvolumeclaims: "3"