apiVersion: v1
kind: ResourceQuota
metadata:
  name: vault-quota
  namespace: vault
spec:
  hard:
    requests.cpu: "3"
    requests.memory: "6Gi"
    limits.cpu: "5"
    limits.memory: "10Gi"
    pods: "6"
    services: "3"
    configmaps: "5"
    secrets: "5"
    persistentvolumeclaims: "6"