apiVersion: v1
kind: ConfigMap
metadata:
  name: database-vault-agent-config
  namespace: database
data:
  config.hcl: |
    exit_after_auth = false
    pid_file = "/home/vault/.pid"

    vault {
      address         = "https://vault.vault.svc:8200"
      ca_cert         = "/vault/ca/vault.ca"
      tls_server_name = "vault-0.vault-internal"
    }

    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role       = "database"
          token_path = "/var/run/secrets/tokens/vault-token"
        }
      }

      sink "file" {
        config = {
          path = "/home/vault/.vault-token"
        }
      }
    }

    template {
      source      = "/etc/vault/mysql-env.tpl"
      destination = "/vault/secrets/mysql-env"
    }

    template_config {
      exit_on_retry_failure = true
    }

  mysql-env.tpl: |
    {{- with secret "kv/data/database/mysql" -}}
    VAL_DB_ROOT={{ .Data.data.MYSQL_ROOT_PASSWORD }}
    VAL_DB_USER={{ .Data.data.MYSQL_USER }}
    VAL_DB_MAIN={{ .Data.data.MYSQL_PASSWORD }}
    {{- end }}
